apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
  namespace: roboshop
data:
  CART_HOST: "cart" 
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    app: payment
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: payment
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: payment
        project: roboshop
        tier: app
    spec:
      containers:
      - name: payment
        image: dockerdevops1994/payment:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment-configmap
        - secretRef:
            name: payment-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-por
  selector:
    app: payment
    project: roboshop
    tier: app
