apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-configmap
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    app: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: shipping
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: dockerdevops1994/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-por
  selector:
    app: shipping
    project: roboshop
    tier: app
