apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: roboshop
data:
  MONGO: "true"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mysql
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mysql
        image: mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql-configmap
        - secretRef:
            name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    project: roboshop
    tier: db

