apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  namespace: roboshop
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: user
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: dockerdevops1994/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-por
  selector:
    app: user
    project: roboshop
    tier: app
