apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
    project: roboshop
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: web
      project: roboshop
      tier: web
  template:
    metadata:
      labels:
        app: web
        project: roboshop
        tier: web
    spec:
      containers:
      - name: web
        image: dockerdevops1994/web:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: web-mount
          mountPath: /etc/nginx
          subPath: nginx.conf
      volumes:
      - name: web-mount
        configMap:
          name: web-config
          items:
            - key: nginx.conf
              value: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec: 
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
    project: roboshop
    tier: web
